import type { ParcelDimensions, DeliveryMethod } from "./pricing"

export type { ParcelDimensions, DeliveryMethod }

export interface OrderDetails {
  orderNumber?: string // This will be the UUID generated by Supabase
  senderName: string
  senderAddress: string
  senderContactNumber: string
  senderEmail: string
  recipientName: string
  recipientAddress: string
  recipientContactNumber: string
  recipientEmail: string
  parcelSize: string
  deliveryMethod: DeliveryMethod
  recipientLine1: string
  recipientLine2?: string
  recipientPostalCode: string
  amount?: number
  status?: string
  isBulkOrder?: boolean
  totalParcels?: number
  totalWeight?: number
  bulkOrderId?: string // For child orders in a bulk order
  redirectUrl?: string // Added for custom redirect URL
  recipients?: RecipientDetails[] // For bulk orders with multiple recipients
}

export interface RecipientDetails {
  name: string
  address: string
  contactNumber: string
  email: string
  line1: string
  line2?: string
  postalCode: string
  parcelIndex: number // To link recipient to specific parcel
  pricingTier?: string // Added pricing tier
}

export type PartialOrderDetails = Partial<OrderDetails>

export interface HitPayRequestBody {
  amount: number
  currency: string
  payment_methods: string[]
  email: string
  name: string
  phone: string
  reference_number: string
  redirect_url: string
  webhook: string
  purpose: string
  // Address removed for privacy reasons
  allow_repeated_payments: boolean
  send_email: boolean
  send_sms: boolean
}

export interface HitPayResponse {
  id: string
  name: string
  email: string
  phone: string
  amount: string
  currency: string
  status: string
  purpose: string
  reference_number: string
  payment_methods: string[]
  url: string
  redirect_url: string
  webhook: string
  send_sms: boolean
  send_email: boolean
  sms_status: string
  email_status: string
  allow_repeated_payments: boolean
  expiry_date: string | null
  created_at: string
  updated_at: string
}

export interface OrderWithParcels {
  orderNumber: string
  shortId?: string
  trackingNumber?: string // Add this field for Detrack tracking number
  senderName: string
  senderAddress: string
  senderContactNumber: string
  senderEmail: string
  recipientName: string
  recipientAddress: string
  recipientContactNumber: string
  recipientEmail: string
  recipientLine1: string
  recipientLine2?: string
  recipientPostalCode: string
  parcelSize: string
  deliveryMethod: string
  amount: number
  status: string
  isBulkOrder: boolean
  parcels: ParcelDimensions[]
  recipients?: RecipientDetails[]
  bulkOrder?: BulkOrderDetails
  totalParcels?: number
  totalWeight?: number
}

export interface RecipientDetails {
  name: string
  address: string
  contactNumber: string
  email: string
  line1: string
  line2?: string
  postalCode: string
  parcelIndex: number
  pricingTier?: string
}

export interface BulkOrderDetails {
  id: string
  totalParcels: number
  totalWeight: number
}

// Update the AddressFormData interface to include recipients
export interface AddressFormData {
  name: string
  contactNumber: string
  email: string
  street: string
  unitNo: string
  postalCode: string
  recipients?: RecipientDetails[] // Add this line
}
